/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from 'react';
import api from '../../services/api';
import { formatMs } from '../../utils/timeFormat';

export default function PracticeReport(){
  const [events,setEvents]=useState([]),[eventId,setEventId]=useState(''),[practices,setPractices]=useState([]),[practiceId,setPracticeId]=useState(''),[result,setResult]=useState(null);
  useEffect(()=>{api.get('/events/').then((res)=>{const data=res.data.data||[];setEvents(data);setEventId(data[0]?.id||'');});},[]);
  useEffect(()=>{if(!eventId)return;api.get(`/practices/events/${eventId}`).then((res)=>{const data=res.data.data||[];setPractices(data);setPracticeId(data[0]?.id||'');});},[eventId]);
  useEffect(()=>{if(!practiceId){setResult(null);return;}api.get(`/public/practice-results/${practiceId}`).then((res)=>setResult(res.data.data));},[practiceId]);
  return <div className="space-y-6"><div className="no-print flex flex-wrap items-end gap-3 rounded-xl border bg-white p-5 shadow-sm"><label className="text-xs font-black uppercase">Event<select className="mt-1 block min-w-64 rounded border p-2 font-normal" value={eventId} onChange={(e)=>setEventId(e.target.value)}>{events.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-xs font-black uppercase">Practice<select className="mt-1 block min-w-64 rounded border p-2 font-normal" value={practiceId} onChange={(e)=>setPracticeId(e.target.value)}>{practices.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="admin-btn-primary" onClick={()=>window.print()}>Print</button></div>
    {result?<div className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="border-b p-6 text-center"><h2 className="text-2xl font-black uppercase">Practice Result</h2><p className="font-bold">{result.practice.name}</p><p className="text-sm text-gray-500">Best run · Maksimal {result.practice.max_runs} run</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-900 text-white"><tr><th className="p-3">Rank</th><th>Practice No</th><th>Race No</th><th className="text-left">Driver</th>{Array.from({length:result.practice.max_runs},(_,i)=><th key={i}>Run {i+1}</th>)}<th>Best Time</th></tr></thead><tbody>{result.entries.map((entry)=><tr key={entry.id} className="border-b"><td className="p-3 text-center font-black">{entry.rank||'-'}</td><td className="text-center font-black">#{entry.practice_start_number}</td><td className="text-center">#{entry.race_start_number}</td><td><span className="font-bold">{entry.driver_name}</span><span className="block text-xs text-gray-500">{entry.vehicle_name}</span></td>{Array.from({length:result.practice.max_runs},(_,i)=>{const run=entry.runs.find((item)=>item.run_no===i+1);return <td key={i} className={`text-center ${entry.best_run_no===i+1?'bg-green-50 font-black text-green-700':''}`}>{run?.finish_time?formatMs(run.elapsed_time_ms):run?.start_time?'OPEN':'-'}</td>;})}<td className="text-center text-base font-black">{entry.best_time_ms?formatMs(entry.best_time_ms):'NO TIME'}</td></tr>)}</tbody></table></div></div>:<div className="rounded-xl border bg-white p-10 text-center text-gray-500">Pilih sesi Practice.</div>}
  </div>;
}
